In [47]:
import numpy as np
import time
import math
a = np.random.randn(3,4)

[[ 0.22107931 -1.31036975  0.10009939 -0.53222844]
 [-0.070519   -0.89991274  0.37456231  1.72301524]
 [ 1.9053153  -1.21688509 -1.26035881  1.48758425]]


In [51]:
print(a)

print(a.sum(axis=1, keepdims=True))

[[ 0.28593813 -0.58271771  0.380115   -1.38718577]
 [-0.00566019 -0.1722607   0.65457791  0.86805791]
 [ 1.97017411 -0.48923304 -0.98034321  0.63262692]]
[[-1.30385036]
 [ 1.34471493]
 [ 1.13322478]]
